name: downstream ci hpc

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      metkit:
        required: false
        type: string
      atlas:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    if: ${{ inputs.eccodes }}
    uses: ecmwf/eccodes/.github/workflows/reusable-ci-hpc.yml@develop
    with:
      eccodes: ${{ inputs.eccodes }}
    secrets: inherit

  eckit:
    name: eckit
    if: ${{ inputs.eckit }}
    uses: ecmwf/eckit/.github/workflows/reusable-ci-hpc.yml@develop
    with:
      eckit: ${{ inputs.eckit }}
    secrets: inherit

  metkit:
    needs: [eckit, eccodes]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.metkit) }}
    name: metkit
    uses: ecmwf/metkit/.github/workflows/reusable-ci-hpc.yml@develop
    with:
      metkit: ${{ inputs.metkit }}
      eckit: ${{ inputs.eckit }}
      eccodes: ${{ inputs.eccodes }}
    secrets: inherit

  atlas:
    needs: [eckit]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.atlas) }}
    name: atlas
    uses: ecmwf/atlas/.github/workflows/reusable-ci-hpc.yml@develop
    with:
      atlas: ${{ inputs.atlas }}
      eckit: ${{ inputs.eckit }}
    secrets: inherit
