name: downstream ci hpc

on:
  workflow_call:
    inputs:
      dev-runner:
        description: Whether to use runner with dev version of build-package-hpc .
        required: false
        type: boolean
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      metkit:
        required: false
        type: string
      atlas:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    if: ${{ inputs.eccodes }}
    runs-on:
      [self-hosted, linux, "${{ inputs.dev-runner && 'hpc-dev' || 'hpc' }}"]
    steps:
      - uses: ecmwf-actions/build-package-hpc@feature/config-file
        with:
          github_user: ${{ secrets.BUILD_PACKAGE_HPC_GITHUB_USER }}
          github_token: ${{ secrets.GH_REPO_READ_TOKEN }}
          troika_user: ${{ secrets.HPC_CI_SSH_USER }}
          repository: ${{ inputs.eccodes }}
          build_config: .github/ci-hpc-config.yml
