name: downstream ci

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      metkit:
        required: false
        type: string
      metkit_sha:
        required: false
        type: string
      atlas:
        required: false
        type: string
    secrets:
      PAT:
        required: true

jobs:
  # eccodes:
  #   name: eccodes
  #   if: ${{ inputs.eccodes }}
  #   uses: ecmwf-enterprise-sandbox/eccodes/.github/workflows/reusable-ci.yml@upstream-ci-self-hosted
  #   secrets: inherit

  # eckit:
  #   name: eckit
  #   if: ${{ inputs.eckit }}
  #   uses: ecmwf-enterprise-sandbox/eckit/.github/workflows/reusable-ci.yml@upstream-ci-self-hosted
  #   secrets: inherit

  metkit:
    # needs: [eccodes, eckit]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.metkit) }}
    name: metkit
    uses: ecmwf/metkit/.github/workflows/reusable-ci.yml@${{ inputs.metkit_sha }}
    with:
      metkit_sha: ${{ inputs.metkit_sha }}
      eccodes: ${{ inputs.eccodes }}
      eckit: ${{ inputs.eckit }}
    secrets: inherit

  # atlas:
  #   needs: [eckit]
  #   if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.atlas) }}
  #   name: atlas
  #   uses: ecmwf-enterprise-sandbox/atlas/.github/workflows/reusable-ci.yml@upstream-ci-self-hosted
  #   with:
  #     eckit: ${{ inputs.eckit }}
  #   secrets: inherit
