name: upstream-ci-hpc

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      metkit:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    if: ${{ inputs.eccodes }}
    uses: ecmwf-enterprise-sandbox/eccodes/.github/workflows/reusable-ci-hpc.yml@upstream-ci-hpc
    secrets: inherit

  metkit:
    # needs eccodes and eckit to complete first, always() ensures that it will run regardless of whether they were successfull and at least one job in needs was successful, or the inputs.metkit is populated
    needs: [eccodes]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.metkit) }}
    name: metkit
    uses: ecmwf-enterprise-sandbox/metkit/.github/workflows/reusable-ci-hpc.yml@upstream-ci-hpc
    with:
      metkit: ${{ inputs.metkit || 'ecmwf-enterprise-sandbox/metkit@upstream-ci-hpc' }}
    secrets: inherit
