name: upstream ci

on:
  workflow_call:
    inputs:
      eckit:
        required: false
        type: string
      eccodes:
        required: false
        type: string
      metkit:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    uses: ecmwf-enterprise-sandbox/eccodes/.github/workflows/reusable-ci.yml@trigger-reusable-upstream-ci

  eckit:
    name: eckit
    uses: ecmwf-enterprise-sandbox/eckit/.github/workflows/reusable-ci.yml@trigger-reusable-upstream-ci

  metkit:
    needs: [eccodes, eckit]
    name: metkit
    uses: ecmwf-enterprise-sandbox/metkit/.github/workflows/reusable-ci.yml@reusable-ci
    with:
      eccodes: ${{ inputs.eccodes }}
      eckit: ${{ inputs.eckit }}
    secrets: inherit

  pgen:
    needs: [metkit]
    name: pgen
    uses: ecmwf-enterprise-sandbox/pgen/.github/workflows/reusable-ci.yml@ci
    with:
      eccodes: ${{ inputs.eccodes }}
      eckit: ${{ inputs.eckit }}
      metkit: ${{ inputs.metkit }}
    secrets: inherit
