name: upstream ci

on:
  workflow_call:
    inputs:
      ecbuild:
        required: false
        type: string
      eccodes:
        required: false
        type: string
      metkit:
        required: false
        type: string

jobs:
  eccodes:
    if: |
      !inputs.eccodes
    name: eccodes
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pretending to build eccodes"

  metkit:
    needs: [eccodes]
    if: |
      always() &&
      !inputs.metkit &&
      (needs.eccodes.result == 'success' || needs.eccodes.result == 'skipped')
    name: metkit
    uses: ecmwf-enterprise-sandbox/metkit/.github/workflows/reusable-ci.yml@reusable-ci
    with:
      eccodes: ${{ inputs.eccodes }}
    secrets: inherit

  pgen:
    needs: [metkit, eccodes]
    if: |
      always() &&
      (needs.eccodes.result == 'success' || needs.eccodes.result == 'skipped') &&
      (needs.metkit.result == 'success' || needs.metkit.result == 'skipped')
    name: pgen
    uses: ecmwf-enterprise-sandbox/pgen/.github/workflows/ci.yml@ci
    with:
      eccodes: ${{ inputs.eccodes }}
      metkit: ${{ inputs.metkit }}
    secrets: inherit
