name: upstream ci hpc

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    if: ${{ inputs.eccodes }}
    uses: ecmwf-enterprise-sandbox/eccodes/.github/workflows/self-hosted-python.yml@self-hosted-python
    secrets: inherit

  eckit:
    name: eckit
    if: ${{ inputs.eckit }}
    uses: ecmwf-enterprise-sandbox/eckit/.github/workflows/reusable-ci-hpc.yml@reusable-ci-hpc # does not exists yet
    secrets: inherit

  metkit:
    # needs eccodes and eckit to complete first, always() ensures that it will run regardless of whether they were successfull and at least one job in needs was successful, or the inputs.metkit is populated
    needs: [eccodes, eckit]
    if: ${{ always() && (contains(join(needs.*.result, ','), 'success') || inputs.metkit) }}
    name: metkit
    uses: ecmwf-enterprise-sandbox/metkit/.github/workflows/self-hosted.yml@upstream-ci-hpc
    secrets: inherit
