name: upstream ci

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      metkit:
        required: false
        type: string
      atlas:
        required: false
        type: string
      mir:
        required: false
        type: string

jobs:
  eccodes:
    name: eccodes
    uses: ecmwf-enterprise-sandbox/eccodes/.github/workflows/reusable-ci.yml@trigger-reusable-upstream-ci
    secrets: inherit

  eckit:
    name: eckit
    uses: ecmwf-enterprise-sandbox/eckit/.github/workflows/reusable-ci.yml@reusable-ci
    secrets: inherit

  metkit:
    needs: [eccodes, eckit]
    name: metkit
    uses: ecmwf-enterprise-sandbox/metkit/.github/workflows/reusable-ci.yml@reusable-ci
    with:
      eccodes: ${{ inputs.eccodes }}
      eckit: ${{ inputs.eckit }}
    secrets: inherit

  atlas:
    needs: [eckit]
    name: atlas
    uses: ecmwf-enterprise-sandbox/atlas/.github/workflows/reusable-ci.yml@reusable-ci
    with:
      eckit: ${{ inputs.eckit }}
    secrets: inherit

  pgen:
    needs: [metkit, atlas]
    name: pgen
    uses: ecmwf-enterprise-sandbox/pgen/.github/workflows/reusable-ci.yml@ci
    with:
      eccodes: ${{ inputs.eccodes }}
      eckit: ${{ inputs.eckit }}
      metkit: ${{ inputs.metkit }}
    secrets: inherit
